[official]
"accountsservice"
"adwaita-icon-theme"
"alacritty"
"alsa-firmware"
"alsa-plugins"
"alsa-utils"
"amd-ucode"
"arc-gtk-theme-eos"
"aspell"
"atuin"
"b43-fwcutter"
"balena-etcher"
"base"
"base-devel"
"bash-completion"
"bat"
"bazecor"
"bind"
"bitwarden-cli"
"bluez"
"bluez-utils"
"btrfs-assistant"
"btrfs-progs"
"cantarell-fonts"
"chezmoi"
"cosmic-app-library"
"cosmic-applets"
"cosmic-bg"
"cosmic-comp"
"cosmic-files"
"cosmic-greeter"
"cosmic-launcher"
"cosmic-notifications"
"cosmic-osd"
"cosmic-panel"
"cosmic-randr"
"cosmic-screenshot"
"cosmic-session"
"cosmic-settings"
"cosmic-settings-daemon"
"cosmic-store"
"cosmic-terminal"
"cosmic-text-editor"
"cosmic-wallpapers"
"cosmic-workspaces"
"cryptsetup"
"cups"
"cups-browsed"
"cups-filters"
"cups-pdf"
"cursor-bin"
"device-mapper"
"diffutils"
"discord"
"dmidecode"
"dmraid"
"dnsmasq"
"dosfstools"
"downgrade"
"dracut"
"duf"
"e2fsprogs"
"efibootmgr"
"efitools"
"endeavouros-keyring"
"endeavouros-mirrorlist"
"endeavouros-theming"
"eos-apps-info"
"eos-dracut"
"eos-hooks"
"eos-log-tool"
"eos-packagelist"
"eos-qogir-icons"
"eos-quickstart"
"eos-rankmirrors"
"eos-settings-gnome"
"ethtool"
"evince"
"exfatprogs"
"eza"
"f2fs-tools"
"fastfetch"
"fd"
"ffmpegthumbnailer"
"firefox"
"firewalld"
"flatpak"
"flatseal"
"foomatic-db"
"foomatic-db-engine"
"foomatic-db-gutenprint-ppds"
"foomatic-db-nonfree"
"foomatic-db-nonfree-ppds"
"foomatic-db-ppds"
"fsarchiver"
"gdm"
"gearlever"
"ghostscript"
"git"
"github-desktop"
"gnome-calculator"
"gnome-calendar"
"gnome-clocks"
"gnome-console"
"gnome-contacts"
"gnome-control-center"
"gnome-disk-utility"
"gnome-keyring"
"gnome-menus"
"gnome-nettool"
"gnome-power-manager"
"gnome-remote-desktop"
"gnome-screenshot"
"gnome-shell"
"gnome-software"
"gnome-system-monitor"
"gnome-text-editor"
"gnome-themes-extra"
"gnome-usage"
"gnome-weather"
"gnumeric"
"go"
"gocryptfs"
"gocryptfs-ui"
"gptfdisk"
"grub"
"grub-btrfs"
"gsfonts"
"gst-libav"
"gst-plugin-pipewire"
"gst-plugins-bad"
"gst-plugins-ugly"
"gutenprint"
"gvfs"
"gvfs-afc"
"gvfs-gphoto2"
"gvfs-mtp"
"gvfs-nfs"
"gvfs-smb"
"haveged"
"hdparm"
"helix"
"hwdetect"
"hwinfo"
"inetutils"
"inotify-tools"
"input-remapper-git"
"inxi"
"iptables-nft"
"iwd"
"jellyfin-media-player"
"jfsutils"
"kitty"
"lazygit"
"less"
"libdvdcss"
"libgsf"
"libopenraw"
"libratbag"
"libreoffice-fresh"
"libwnck3"
"linux"
"linux-firmware"
"linux-headers"
"linux-lts"
"linux-lts-headers"
"logrotate"
"loupe"
"lsb-release"
"lsscsi"
"luarocks"
"lvm2"
"man-db"
"man-pages"
"mdadm"
"meld"
"mesa-utils"
"microsoft-edge-stable-bin"
"mlocate"
"modemmanager"
"mtools"
"multitail"
"nano"
"nano-syntax-highlighting"
"nautilus"
"nautilus-sendto"
"neovim"
"neovim-web-devicons-git"
"netctl"
"networkmanager"
"networkmanager-openconnect"
"networkmanager-openvpn"
"nfs-utils"
"nilfs-utils"
"noto-fonts"
"noto-fonts-cjk"
"noto-fonts-emoji"
"noto-fonts-extra"
"nss-mdns"
"ntfs-3g"
"ntp"
"openssh"
"os-prober"
"pacman-contrib"
"paru"
"pavucontrol"
"perl"
"pinta"
"pipewire-alsa"
"pipewire-jack"
"pipewire-pulse"
"pkgfile"
"poppler-glib"
"power-profiles-daemon"
"pv"
"python"
"python-capng"
"python-defusedxml"
"python-packaging"
"python-pyqt5"
"python-virtualenv"
"rebuild-detector"
"reflector"
"reflector-simple"
"reiserfsprogs"
"ripgrep"
"rsync"
"rtkit"
"rust"
"s-nail"
"sddm"
"sg3_utils"
"shellcheck"
"smartmontools"
"snap-pac"
"snap-pac-grub"
"snapper"
"snapper-gui-git"
"sof-firmware"
"splix"
"steam"
"sublime-text-4"
"sudo"
"sushi"
"sysfsutils"
"system-config-printer"
"systemd-sysvcompat"
"terminus-font"
"texinfo"
"thunar"
"thunderbird"
"tldr"
"tmux"
"totem"
"tree"
"ttf-bitstream-vera"
"ttf-dejavu"
"ttf-liberation"
"ttf-meslo-nerd"
"ttf-opensans"
"ueberzug"
"unrar"
"unzip"
"update-grub"
"upower"
"usb_modeswitch"
"usbutils"
"vi"
"vim"
"visual-studio-code-bin"
"welcome"
"wezterm"
"wget"
"which"
"wireplumber"
"wpa_supplicant"
"xclip"
"xdg-desktop-portal"
"xdg-desktop-portal-cosmic"
"xdg-desktop-portal-gnome"
"xdg-user-dirs"
"xdg-user-dirs-gtk"
"xdg-utils"
"xf86-input-libinput"
"xf86-video-amdgpu"
"xf86-video-ati"
"xfsprogs"
"xl2tpd"
"xorg-server"
"xorg-xdpyinfo"
"xorg-xinit"
"xorg-xinput"
"xorg-xkill"
"xorg-xrandr"
"xorg-xsetroot"
"yay"
"yazi"
"zellij"
"zen-browser-avx2-bin"
"zoxide"
[aur]
"balena-etcher"
"bazecor"
"btrfs-assistant"
"cursor-bin"
"flatseal"
"gearlever"
"github-desktop"
"gocryptfs-ui"
"input-remapper-git"
"jellyfin-media-player"
"libart-lgpl"
"libglade"
"microsoft-edge-stable-bin"
"multitail"
"nautilus-sendto"
"neovim-web-devicons-git"
"nvm"
"rest"
"scripthaus"
"snap-pac-grub"
"snapper-gui-git"
"sublime-text-4"
"update-grub"
"visual-studio-code-bin"
"zen-browser-avx2-bin"
[groups]
"cosmic"
"gnome"
"neovim-plugins"
"nerd-fonts"
"pro-audio"
"pyqt5"
"python-build-backend"
"qt5"
"qt6"
"tree-sitter-grammars"
"vulkan-devel"
"xfce4"
"xorg"
"xorg-apps"
"xorg-drivers"
"xorg-fonts"
