# Update list created on Wed 11 Sep 2024 07:25:33 AM EDT
# Add packages in the format: "package_name" = ""
"fastfetch" = ""
"iwd" = ""
"firefox" = ""
"discord" = ""
"cursor" = ""
"zen" = ""
"thunderbird" = ""
"kitty" = ""
"alacrity" = ""
"neovim" = ""
