[install]
auto_run = false

[variables]
COUNTRY_ISO = "CA"
DESKTOP_ENVIRONMENT = "cosmic"
DEVICE = "/dev/nvme0n1"
EDITOR = "nvim"
FORMAT_TYPE = "btrfs"
GPU = "amd"
GPU_DRIVER = "amdgpu"
HOSTNAME = "angryguy"
INSTALL_DEVICE = "/dev/nvme0n1"
KEYMAP = "us"
LOCALE = "en_US.UTF-8"
LUKS = "false"
LUKS_PASSWORD = ""
MICROCODE = "amd"
MOUNT_OPTIONS = "noatime,compress=zstd,ssd,commit=120"
PARTITION_BIOSBOOT = "/dev/nvme0n1"
PARTITION_EFI = "/dev/nvme0n1p2"
PARTITION_HOME = "/dev/nvme0n1p4"
PARTITION_ROOT = "/dev/nvme0n1p3"
PARTITION_SWAP = "/dev/nvme0n1p5"
PASSWORD = "password"
SHELL = "bash"
SUBVOLUMES = "@,@home,@var,@.snapshots"
TERMINAL = "alacritty"
TIMEZONE = "America/Toronto"
USERNAME = "ssnow"
