format = """
[\u2502](bold green)\
$os\
[\u2591\u2592\u2593](#3B4252)\
$python\
$username\
[\ue0b0](bg:#434C5E fg:#3B4252)\
$directory\
[\ue0b0](fg:#434C5E bg:#4C566A)\
$git_branch\
$git_status\
[\ue0b0](fg:#4C566A bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$php\
[\ue0b0](fg:#86BBD8 bg:#06969A)\
$docker_context\
[\ue0b0](fg:#06969A bg:#33658A)\
$time\
[\ue0b4 ](fg:#33658A)\
\n$character"""

command_timeout = 5000

palette = 'catppuccin_mocha'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# Disable the blank line at the start of the prompt
# add_newline = false

# Disable/Enable line break
#[line_break]
#disabled = true

# Get editor completions based on the config schema
#"$schema" = 'https://starship.rs/config-schema.json'

# Replace the '\u276f' symbol in the prompt with '\u279c'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[\u2514\u2500>](bold green)' # The 'success_symbol' segment is being set to '\u279c' with the color 'bold green'
error_symbol = '[\uf432](bold fg:red)'
vimcmd_symbol = '[\uf434](bold fg:creen)'
vimcmd_replace_one_symbol = '[\uf434](bold fg:purple)'
vimcmd_replace_symbol = '[\uf434](bold fg:purple)'
vimcmd_visual_symbol = '[\uf434](bold fg:lavender)'

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "\U000f0372"
Ubuntu = "\U000f0548"
SUSE = "\uf314"
Raspbian = "\U000f043f"
Mint = "\U000f08ed"
Macos = "\ue61f"
Manjaro = "\uf312"
Linux = "\U000f033d"
Gentoo = "\U000f08e8"
Fedora = "\U000f08db"
Alpine = "\uf300"
Amazon = "\uf270"
Android = "\ue70e"
Arch = "\U000f08c7"
Artix = "\U000f08c7"
CentOS = "\uf304"
Debian = "\U000f08da"
Redhat = "\U000f111b"
RedHatEnterprise = "\U000f111b"

# You can also replace your username with a neat symbol like \uf120 to save some space
[username]
show_always = true
style_user = "bg:#3B4252"
style_root = "red bold"
format = '[$user ]($style)'

[sudo]
style = 'bold green'
symbol = '\U0001f9d9 \U0001f4bb '
disabled = false

[directory]
style = "bg:#434C5E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "\u2026/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "\uf718 "
"Downloads" = "\uf019 "
"Music" = "\uf001 "
"Pictures" = "\uf03e "
# Keep in mind that the order matters. For example:
# "Important Documents" = " \uf718\uf12a "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important \uf718 " = " \uf718\uf12a "

[c]
symbol = "\ue61e "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "\uf308 "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "\ue275 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "\ue62c "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "\uf418"
style = "bg:#4C566A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#4C566A"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "\ue627 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "\ue777 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "\ue256 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "\ue624 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "\ue718"
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "\uf6a4 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#3B4252"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = "\ue7a8"
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = "\ue608"
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
use_12hr = true
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ \uf43a $time ]($style)'